version: '3'
services:
  selenium:
    image: selenium/standalone-chrome-debug
    ports:
      - 4444:4444
      - 5901:5900      
  website:
   build:
    context: .
   ports:
    - 80:80
  unit-tests:
    build:
      dockerfile: rspec.dockerfile
      context: .
    environment:
      SELENIUM_HOST: selenium
      SELENIUM_PORT: 4444
    volumes:
      - $PWD:/home/alex/Docker
    command:
      - --pattern
      - /home/alex/Docker/spec/unit/*_spec.rb

